name: Deploy to Docker

on:
  push:
    branches:
      - main
  release:
    types: [published]  # Trigger on release publish

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Determine Docker Tag
        id: get_tag
        run: |
          # Check if the reference is a tag
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF##refs/tags/}"
          else
            TAG="develop"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - 
        name: Build and push Docker image
        env:
          TAG: ${{ env.TAG }}
        run: |
          docker build -t unit-econ:$TAG .
          docker tag unit-econ:$TAG ${{ secrets.DOCKER_USERNAME }}/unit-econ:$TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/unit-econ:$TAG

      # -
      #   name: Retrieve SSH key
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      # -
      #   name: Copy files to DigitalOcean
      #   run: |
      #     scp  -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./docker-compose.yml ./nginx ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/app
      # -
      #   name: Deploy with appleboy
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{secrets.SSH_KEY}}
      #     script: |
      #       cd ~/app
      #       export $(cat .env|xargs)
      #       docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}
      #       docker pull ${{ secrets.DOCKER_USERNAME }}/unit-econ:v1.0.0
      #       docker compose up -d
      -
        name: Notify deployment status
        run: echo "Deployment to dockerhub complete"
